exclude: '.*snap$'
repos:
- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v2.0.0
  hooks:
    - id: trailing-whitespace
      exclude_types: [pem]
    - id: check-merge-conflict
    - id: debug-statements
    - id: flake8
      exclude: '.*migrations.*'
      additional_dependencies: [
        'flake8-blind-except',
        'flake8-comprehensions',
        'flake8-pep3101',
        'flake8-tidy-imports',
      ]
- repo: https://github.com/pre-commit/mirrors-isort
  rev: v4.3.20
  hooks:
    - id: isort
      exclude: '^.*migrations.*$'
- repo: https://github.com/ambv/black
  rev: 19.3b0
  hooks:
    - id: black
      args: [--line-length=100, --safe]
      exclude: '^.*migrations.*$'
- repo: local
  hooks:
    - id: prettier
      name: prettier
      files: '^.*\.(j|t)sx?$'
      language: system
      pass_filenames: true
      entry: ./node_modules/.bin/prettier --config=.prettierrc.yaml --write
- repo: local
  hooks:
  - id: eslint
    name: eslint
    files: '^.*\.(j|t)sx?$'
    language: system
    pass_filenames: true
    entry: ./node_modules/.bin/eslint -c "./.eslintrc" --color